# This file exists so Dependabot can track BusyBox image tag updates.
# To refresh the committed binary asset:
# docker run --rm --platform=linux/amd64 busybox:1.36.1-musl cat /bin/busybox > test/e2e/assets/busybox/v1.36.1/busybox-linux-amd64
FROM busybox:1.36.1-musl
