//go:build linux

package disk

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/telekom/BOOTy/pkg/config"
)

// ApplyPartitionLayout creates partitions on a disk according to the layout.
// Uses sgdisk for GPT and sfdisk for MBR.
func (m *Manager) ApplyPartitionLayout(ctx context.Context, device string, layout *config.PartitionLayout) error {
	slog.Info("Applying partition layout", "device", device, "table", layout.Table, "partitions", len(layout.Partitions))

	// Zap existing partition table.
	if _, err := m.cmd.Run(ctx, "sgdisk", "--zap-all", device); err != nil {
		return fmt.Errorf("zapping partition table: %w", err)
	}

	for i, part := range layout.Partitions {
		num := i + 1
		typeGUID := resolveTypeGUID(part)

		// Build sgdisk --new argument: partnum:start:end
		var sizeArg string
		if part.SizeMB > 0 {
			sizeArg = fmt.Sprintf("0:+%dM", part.SizeMB)
		} else {
			sizeArg = "0:0" // fill remaining
		}

		args := []string{
			fmt.Sprintf("--new=%d:%s", num, sizeArg),
			fmt.Sprintf("--typecode=%d:%s", num, typeGUID),
		}
		if part.Label != "" {
			args = append(args, fmt.Sprintf("--change-name=%d:%s", num, part.Label))
		}
		args = append(args, device)

		if _, err := m.cmd.Run(ctx, "sgdisk", args...); err != nil {
			return fmt.Errorf("creating partition %d (%s): %w", num, part.Label, err)
		}
		slog.Info("Created partition", "num", num, "label", part.Label, "sizeMB", part.SizeMB, "fs", part.Filesystem)
	}

	// Re-read partition table.
	if err := m.PartProbe(ctx, device); err != nil {
		return fmt.Errorf("partprobe after layout: %w", err)
	}

	// Format partitions.
	for i, part := range layout.Partitions {
		if part.Filesystem == "" {
			continue
		}
		partDev := partitionDevice(device, i+1)
		if err := m.formatPartition(ctx, partDev, part.Filesystem); err != nil {
			return fmt.Errorf("formatting partition %d: %w", i+1, err)
		}
	}

	return nil
}

// GenerateFstab creates an fstab file for the partition layout.
func GenerateFstab(layout *config.PartitionLayout, device string) string {
	var sb strings.Builder
	sb.WriteString("# Generated by BOOTy\n")
	for i, part := range layout.Partitions {
		if part.Mountpoint == "" {
			continue
		}
		partDev := partitionDevice(device, i+1)
		fsType := part.Filesystem
		if fsType == "" {
			fsType = "auto"
		}
		opts := "defaults"
		dump, pass := 0, 0
		if part.Mountpoint == "/" {
			pass = 1
		} else if part.Mountpoint == "/boot/efi" {
			opts = "umask=0077"
			pass = 2
		} else {
			pass = 2
		}
		fmt.Fprintf(&sb, "%s\t%s\t%s\t%s\t%d\t%d\n", partDev, part.Mountpoint, fsType, opts, dump, pass)
	}
	return sb.String()
}

// resolveTypeGUID returns the GPT type GUID for a partition.
func resolveTypeGUID(part config.Partition) string {
	if part.TypeGUID != "" {
		return part.TypeGUID
	}
	switch part.Filesystem {
	case "vfat":
		return EFISystemPartitionGUID
	case "swap":
		return "0657FD6D-A4AB-43C4-84E5-0933C84B4F4F" // Linux swap
	default:
		return LinuxFilesystemGUID
	}
}

// partitionDevice returns the device path for a specific partition number.
func partitionDevice(device string, num int) string {
	// NVMe: /dev/nvme0n1 → /dev/nvme0n1p1
	// SATA: /dev/sda → /dev/sda1
	if strings.Contains(device, "nvme") || strings.Contains(device, "loop") || strings.Contains(device, "mmcblk") {
		return fmt.Sprintf("%sp%d", device, num)
	}
	return fmt.Sprintf("%s%d", device, num)
}

// formatPartition runs mkfs for the given filesystem type.
func (m *Manager) formatPartition(ctx context.Context, device, fsType string) error {
	slog.Info("Formatting partition", "device", device, "filesystem", fsType)
	var err error
	switch fsType {
	case "vfat":
		_, err = m.cmd.Run(ctx, "mkfs.vfat", "-F", "32", device)
	case "ext4":
		_, err = m.cmd.Run(ctx, "mkfs.ext4", "-F", device)
	case "xfs":
		_, err = m.cmd.Run(ctx, "mkfs.xfs", "-f", device)
	case "swap":
		_, err = m.cmd.Run(ctx, "mkswap", device)
	default:
		return fmt.Errorf("unsupported filesystem: %s", fsType)
	}
	return err
}
