//go:build linux

package disk

import (
	"context"
	"fmt"
	"log/slog"
	"path/filepath"
	"strings"

	"github.com/telekom/BOOTy/pkg/config"
)

// LinuxLVMGUID is the GPT type GUID for Linux LVM partitions.
const LinuxLVMGUID = "E6D6D379-F507-44C2-A23C-238F2A3DF928"

// ApplyPartitionLayout creates partitions on a disk according to the layout.
// Only GPT partition tables are supported (via sgdisk).
func (m *Manager) ApplyPartitionLayout(ctx context.Context, device string, layout *config.PartitionLayout) error {
	if layout == nil {
		return fmt.Errorf("partition layout is nil")
	}
	if device == "" {
		return fmt.Errorf("device path is empty")
	}
	if len(layout.Partitions) == 0 {
		return fmt.Errorf("partition layout has no partitions")
	}
	if layout.Table != "" && layout.Table != "gpt" {
		return fmt.Errorf("unsupported partition table type %q, only \"gpt\" is supported", layout.Table)
	}

	slog.Info("Applying partition layout", "device", device, "table", layout.Table, "partitions", len(layout.Partitions))

	// Zap existing partition table.
	if out, err := m.cmd.Run(ctx, "sgdisk", "--zap-all", device); err != nil {
		return fmt.Errorf("zapping partition table: %s: %w", string(out), err)
	}

	for i, part := range layout.Partitions {
		num := i + 1
		typeGUID := resolveTypeGUID(part)
		if isLVMPVPartition(layout, num) {
			typeGUID = LinuxLVMGUID
		}

		// Build sgdisk --new argument: partnum:start:end
		var sizeArg string
		if part.SizeMB > 0 {
			sizeArg = fmt.Sprintf("0:+%dM", part.SizeMB)
		} else {
			sizeArg = "0:0" // fill remaining
		}

		args := []string{
			fmt.Sprintf("--new=%d:%s", num, sizeArg),
			fmt.Sprintf("--typecode=%d:%s", num, typeGUID),
		}
		if part.Label != "" {
			args = append(args, fmt.Sprintf("--change-name=%d:%s", num, part.Label))
		}
		args = append(args, device)

		if out, err := m.cmd.Run(ctx, "sgdisk", args...); err != nil {
			return fmt.Errorf("creating partition %d (%s): %s: %w", num, part.Label, string(out), err)
		}
		slog.Info("Created partition", "num", num, "label", part.Label, "sizeMB", part.SizeMB, "fs", part.Filesystem)
	}

	// Re-read partition table.
	if err := m.PartProbe(ctx, device); err != nil {
		return fmt.Errorf("partprobe after layout: %w", err)
	}

	if err := m.formatLayoutPartitions(ctx, device, layout); err != nil {
		return err
	}

	return nil
}

func (m *Manager) formatLayoutPartitions(ctx context.Context, device string, layout *config.PartitionLayout) error {
	for i, part := range layout.Partitions {
		partNum := i + 1
		if isLVMPVPartition(layout, partNum) {
			slog.Info("Skipping format for LVM PV partition", "partition", partNum, "label", part.Label)
			continue
		}
		if part.Filesystem == "" {
			continue
		}
		partDev := partitionDevice(device, partNum)
		if err := m.formatPartition(ctx, partDev, part.Filesystem); err != nil {
			return fmt.Errorf("formatting partition %d: %w", partNum, err)
		}
	}
	return nil
}

func isLVMPVPartition(layout *config.PartitionLayout, partNum int) bool {
	return layout != nil && layout.LVM != nil && layout.LVM.PVPartition == partNum
}

// GenerateFstab creates an fstab file for the partition layout.
func GenerateFstab(layout *config.PartitionLayout, device string) string {
	if layout == nil {
		return ""
	}
	var sb strings.Builder
	sb.WriteString("# Generated by BOOTy\n")
	for i, part := range layout.Partitions {
		if part.Mountpoint == "" && part.Filesystem != "swap" {
			continue
		}
		partDev := partitionDevice(device, i+1)
		fsSpec := partitionFstabSpec(part, partDev)
		fsType := part.Filesystem
		if fsType == "" {
			fsType = "auto"
		}
		// Swap partitions use "none" as mountpoint and "sw" as options.
		if fsType == "swap" {
			fmt.Fprintf(&sb, "%s\tnone\tswap\tsw\t0\t0\n", fsSpec)
			continue
		}
		opts := "defaults"
		dump, pass := 0, 0
		switch part.Mountpoint {
		case "/":
			pass = 1
		case "/boot/efi":
			opts = "umask=0077"
			pass = 2
		default:
			pass = 2
		}
		fmt.Fprintf(&sb, "%s\t%s\t%s\t%s\t%d\t%d\n", fsSpec, part.Mountpoint, fsType, opts, dump, pass)
	}
	return sb.String()
}

func partitionFstabSpec(part config.Partition, fallbackDevice string) string {
	if part.Label == "" {
		return fallbackDevice
	}
	return "PARTLABEL=" + escapeFstabValue(part.Label)
}

func escapeFstabValue(value string) string {
	replacer := strings.NewReplacer(
		"\\", "\\\\",
		" ", "\\040",
		"\t", "\\011",
		"\n", "\\012",
		"#", "\\043",
	)
	return replacer.Replace(value)
}

// resolveTypeGUID returns the GPT type GUID for a partition.
func resolveTypeGUID(part config.Partition) string {
	if part.TypeGUID != "" {
		return part.TypeGUID
	}
	switch part.Filesystem {
	case "vfat":
		return EFISystemPartitionGUID
	case "swap":
		return "0657FD6D-A4AB-43C4-84E5-0933C84B4F4F" // Linux swap
	default:
		return LinuxFilesystemGUID
	}
}

// PartitionDevicePath returns the device path for a specific partition number.
func PartitionDevicePath(device string, num int) string {
	// NVMe: /dev/nvme0n1 → /dev/nvme0n1p1
	// SATA: /dev/sda → /dev/sda1
	devName := filepath.Base(device)
	if strings.HasPrefix(devName, "nvme") || strings.HasPrefix(devName, "loop") || strings.HasPrefix(devName, "mmcblk") || strings.HasPrefix(devName, "md") || strings.HasPrefix(devName, "nbd") {
		return fmt.Sprintf("%sp%d", device, num)
	}
	return fmt.Sprintf("%s%d", device, num)
}

// partitionDevice is an unexported alias for internal use.
func partitionDevice(device string, num int) string {
	return PartitionDevicePath(device, num)
}

// formatPartition runs mkfs for the given filesystem type.
func (m *Manager) formatPartition(ctx context.Context, device, fsType string) error {
	slog.Info("Formatting partition", "device", device, "filesystem", fsType)
	var out []byte
	var err error
	switch fsType {
	case "vfat":
		out, err = m.cmd.Run(ctx, "mkfs.vfat", "-F", "32", device)
	case "ext4":
		out, err = m.cmd.Run(ctx, "mkfs.ext4", "-F", device)
	case "xfs":
		out, err = m.cmd.Run(ctx, "mkfs.xfs", "-f", device)
	case "swap":
		out, err = m.cmd.Run(ctx, "mkswap", device)
	default:
		return fmt.Errorf("unsupported filesystem: %s", fsType)
	}
	if err != nil {
		cmd := fmt.Sprintf("mkfs.%s", fsType)
		if fsType == "swap" {
			cmd = "mkswap"
		}
		return fmt.Errorf("%s %s: %s: %w", cmd, device, string(out), err)
	}
	return nil
}
