//go:build linux

package provision

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"strings"
)

// persistNetworkStep is the provisioning step wrapper for network persistence.
func (o *Orchestrator) persistNetworkStep(_ context.Context) error {
	return o.persistNetworkConfig()
}

// persistNetworkConfig writes the current network configuration into the
// target OS filesystem so networking works on first boot.
func (o *Orchestrator) persistNetworkConfig() error {
	if !o.cfg.PersistNetwork {
		return nil
	}

	rootDir := "/newroot"
	osFamily := o.cfg.OSFamily
	if osFamily == "" {
		osFamily = detectOSFamily(rootDir)
	}

	o.log.Info("Persisting network configuration", "os_family", osFamily)

	switch osFamily {
	case "ubuntu":
		return writeNetplan(rootDir, o.cfg.StaticIP, o.cfg.StaticGateway, o.cfg.DNSResolvers)
	case "flatcar":
		return writeSystemdNetworkd(rootDir, o.cfg.StaticIP, o.cfg.StaticGateway, o.cfg.DNSResolvers)
	default:
		return writeNetplan(rootDir, o.cfg.StaticIP, o.cfg.StaticGateway, o.cfg.DNSResolvers)
	}
}

// detectOSFamily reads /etc/os-release in the chroot to determine the OS.
func detectOSFamily(rootDir string) string {
	data, err := os.ReadFile(filepath.Join(rootDir, "etc", "os-release"))
	if err != nil {
		slog.Warn("Could not read os-release, defaulting to ubuntu", "error", err)
		return "ubuntu"
	}
	content := strings.ToLower(string(data))
	switch {
	case strings.Contains(content, "ubuntu"):
		return "ubuntu"
	case strings.Contains(content, "flatcar"):
		return "flatcar"
	case strings.Contains(content, "rhel"), strings.Contains(content, "centos"), strings.Contains(content, "rocky"):
		return "rhel"
	default:
		return "ubuntu"
	}
}

// writeNetplan generates a netplan YAML config for Ubuntu/Debian systems.
func writeNetplan(rootDir, staticIP, gateway, dnsResolvers string) error {
	netplanDir := filepath.Join(rootDir, "etc", "netplan")
	if err := os.MkdirAll(netplanDir, 0755); err != nil {
		return fmt.Errorf("create netplan directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("# Generated by BOOTy provisioner — do not edit\n")
	buf.WriteString("network:\n")
	buf.WriteString("  version: 2\n")
	buf.WriteString("  renderer: networkd\n")

	iface := detectPrimaryInterface()
	if staticIP != "" {
		buf.WriteString("  ethernets:\n")
		buf.WriteString(fmt.Sprintf("    %s:\n", iface))
		buf.WriteString(fmt.Sprintf("      addresses: [%q]\n", staticIP))
		if gateway != "" {
			ip, _, err := net.ParseCIDR(gateway)
			if err != nil {
				ip = net.ParseIP(gateway)
			}
			if ip != nil {
				buf.WriteString(fmt.Sprintf("      gateway4: %s\n", ip))
			}
		}
		if dnsResolvers != "" {
			buf.WriteString("      nameservers:\n")
			buf.WriteString(fmt.Sprintf("        addresses: [%s]\n", dnsResolvers))
		}
	} else {
		buf.WriteString("  ethernets:\n")
		buf.WriteString(fmt.Sprintf("    %s:\n", iface))
		buf.WriteString("      dhcp4: true\n")
	}

	return os.WriteFile(filepath.Join(netplanDir, "01-booty-provisioned.yaml"), []byte(buf.String()), 0600)
}

// writeSystemdNetworkd generates systemd-networkd .network files for Flatcar.
func writeSystemdNetworkd(rootDir, staticIP, gateway, dnsResolvers string) error {
	networkDir := filepath.Join(rootDir, "etc", "systemd", "network")
	if err := os.MkdirAll(networkDir, 0755); err != nil {
		return fmt.Errorf("create systemd network directory: %w", err)
	}

	iface := detectPrimaryInterface()
	var buf strings.Builder
	buf.WriteString("# Generated by BOOTy provisioner\n")
	buf.WriteString("[Match]\n")
	buf.WriteString(fmt.Sprintf("Name=%s\n\n", iface))
	buf.WriteString("[Network]\n")

	if staticIP != "" {
		buf.WriteString(fmt.Sprintf("Address=%s\n", staticIP))
		if gateway != "" {
			ip, _, err := net.ParseCIDR(gateway)
			if err != nil {
				ip = net.ParseIP(gateway)
			}
			if ip != nil {
				buf.WriteString(fmt.Sprintf("Gateway=%s\n", ip))
			}
		}
		if dnsResolvers != "" {
			for _, dns := range strings.Split(dnsResolvers, ",") {
				dns = strings.TrimSpace(dns)
				if dns != "" {
					buf.WriteString(fmt.Sprintf("DNS=%s\n", dns))
				}
			}
		}
	} else {
		buf.WriteString("DHCP=yes\n")
	}

	return os.WriteFile(filepath.Join(networkDir, "10-booty.network"), []byte(buf.String()), 0644)
}

// detectPrimaryInterface returns the name of the first non-loopback interface.
func detectPrimaryInterface() string {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "eth0"
	}
	for _, iface := range ifaces {
		if iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		if iface.Flags&net.FlagUp != 0 {
			return iface.Name
		}
	}
	return "eth0"
}
