//go:build linux

package provision

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"strings"
)

// persistNetworkStep is the provisioning step wrapper for network persistence.
func (o *Orchestrator) persistNetworkStep(_ context.Context) error {
	return o.persistNetworkConfig()
}

// persistNetworkConfig writes the current network configuration into the
// target OS filesystem so networking works on first boot.
func (o *Orchestrator) persistNetworkConfig() error {
	if !o.cfg.PersistNetwork {
		return nil
	}

	rootDir := "/newroot"
	osFamily := o.cfg.OSFamily
	if osFamily == "" {
		osFamily = detectOSFamily(rootDir)
	}

	o.log.Info("Persisting network configuration", "os_family", osFamily)

	iface := o.cfg.StaticIface
	if iface == "" {
		iface = detectPrimaryInterface()
	}

	switch osFamily {
	case "ubuntu":
		return writeNetplan(rootDir, iface, o.cfg.StaticIP, o.cfg.StaticGateway, o.cfg.DNSResolvers)
	case "flatcar":
		return writeSystemdNetworkd(rootDir, iface, o.cfg.StaticIP, o.cfg.StaticGateway, o.cfg.DNSResolvers)
	case "rhel":
		o.log.Warn("Network persistence not yet supported for RHEL-based systems, skipping")
		return nil
	default:
		return writeNetplan(rootDir, iface, o.cfg.StaticIP, o.cfg.StaticGateway, o.cfg.DNSResolvers)
	}
}

// detectOSFamily reads /etc/os-release in the chroot to determine the OS.
func detectOSFamily(rootDir string) string {
	data, err := os.ReadFile(filepath.Join(rootDir, "etc", "os-release"))
	if err != nil {
		slog.Warn("Could not read os-release, defaulting to ubuntu", "error", err)
		return "ubuntu"
	}
	content := strings.ToLower(string(data))
	switch {
	case strings.Contains(content, "ubuntu"):
		return "ubuntu"
	case strings.Contains(content, "flatcar"):
		return "flatcar"
	case strings.Contains(content, "rhel"), strings.Contains(content, "centos"), strings.Contains(content, "rocky"):
		return "rhel"
	default:
		return "ubuntu"
	}
}

// writeNetplan generates a netplan YAML config for Ubuntu/Debian systems.
func writeNetplan(rootDir, iface, staticIP, gateway, dnsResolvers string) error {
	netplanDir := filepath.Join(rootDir, "etc", "netplan")
	if err := os.MkdirAll(netplanDir, 0o755); err != nil {
		return fmt.Errorf("create netplan directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("# Generated by BOOTy provisioner — do not edit\n")
	buf.WriteString("network:\n")
	buf.WriteString("  version: 2\n")
	buf.WriteString("  renderer: networkd\n")

	buf.WriteString("  ethernets:\n")
	fmt.Fprintf(&buf, "    %s:\n", iface)

	if staticIP == "" {
		buf.WriteString("      dhcp4: true\n")
	} else {
		writeNetplanStatic(&buf, staticIP, gateway, dnsResolvers)
	}

	return os.WriteFile(filepath.Join(netplanDir, "01-booty-provisioned.yaml"), []byte(buf.String()), 0o600)
}

// writeNetplanStatic writes static IP configuration into a netplan buffer.
func writeNetplanStatic(buf *strings.Builder, staticIP, gateway, dnsResolvers string) {
	fmt.Fprintf(buf, "      addresses: [%q]\n", staticIP)
	if gateway != "" {
		ip := parseGateway(gateway)
		if ip != nil {
			if ip.To4() != nil {
				fmt.Fprintf(buf, "      gateway4: %s\n", ip)
			} else {
				fmt.Fprintf(buf, "      gateway6: %s\n", ip)
			}
		}
	}
	if dnsResolvers != "" {
		buf.WriteString("      nameservers:\n")
		buf.WriteString("        addresses: [")
		first := true
		for _, dns := range strings.Split(dnsResolvers, ",") {
			dns = strings.TrimSpace(dns)
			if dns == "" {
				continue
			}
			if !first {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%q", dns)
			first = false
		}
		buf.WriteString("]\n")
	}
}

// writeSystemdNetworkd generates systemd-networkd .network files for Flatcar.
func writeSystemdNetworkd(rootDir, iface, staticIP, gateway, dnsResolvers string) error {
	networkDir := filepath.Join(rootDir, "etc", "systemd", "network")
	if err := os.MkdirAll(networkDir, 0o755); err != nil {
		return fmt.Errorf("create systemd network directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("# Generated by BOOTy provisioner\n")
	buf.WriteString("[Match]\n")
	fmt.Fprintf(&buf, "Name=%s\n\n", iface)
	buf.WriteString("[Network]\n")

	if staticIP == "" {
		buf.WriteString("DHCP=yes\n")
	} else {
		writeNetworkdStatic(&buf, staticIP, gateway, dnsResolvers)
	}

	return os.WriteFile(filepath.Join(networkDir, "10-booty.network"), []byte(buf.String()), 0o644)
}

// writeNetworkdStatic writes static IP configuration into a systemd-networkd buffer.
func writeNetworkdStatic(buf *strings.Builder, staticIP, gateway, dnsResolvers string) {
	fmt.Fprintf(buf, "Address=%s\n", staticIP)
	if gateway != "" {
		ip := parseGateway(gateway)
		if ip != nil {
			fmt.Fprintf(buf, "Gateway=%s\n", ip)
		}
	}
	if dnsResolvers != "" {
		for _, dns := range strings.Split(dnsResolvers, ",") {
			dns = strings.TrimSpace(dns)
			if dns != "" {
				fmt.Fprintf(buf, "DNS=%s\n", dns)
			}
		}
	}
}

// parseGateway extracts a net.IP from a gateway string or CIDR.
func parseGateway(gateway string) net.IP {
	ip, _, err := net.ParseCIDR(gateway)
	if err != nil {
		ip = net.ParseIP(gateway)
	}
	return ip
}

// detectPrimaryInterface returns the name of the first non-loopback interface.
func detectPrimaryInterface() string {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "eth0"
	}
	for _, iface := range ifaces {
		if iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		if iface.Flags&net.FlagUp != 0 {
			return iface.Name
		}
	}
	return "eth0"
}
