//go:build linux

package provision

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/telekom/BOOTy/pkg/config"
)

// safeNetName validates that a network name (interface, VLAN ID) is safe for use in file paths.
var safeNetName = regexp.MustCompile(`^[a-zA-Z0-9._-]+$`)

func validateNetName(name string) error {
	if name == "" || !safeNetName.MatchString(name) || strings.Contains(name, "..") {
		return fmt.Errorf("invalid network name %q: must contain only alphanumeric, dot, dash, underscore", name)
	}
	return nil
}

// persistNetworkStep is the provisioning step wrapper for network persistence.
func (o *Orchestrator) persistNetworkStep(_ context.Context) error {
	return o.persistNetworkConfig()
}

// persistNetworkConfig writes the current network configuration into the
// target OS filesystem so networking works on first boot.
func (o *Orchestrator) persistNetworkConfig() error {
	if !o.cfg.PersistNetwork {
		return nil
	}

	rootDir := newroot
	osFamily := o.cfg.OSFamily
	if osFamily == "" {
		osFamily = detectOSFamily(rootDir)
	}

	o.log.Info("Persisting network configuration", "os_family", osFamily)

	iface := o.cfg.StaticIface
	if iface == "" {
		iface = detectPrimaryInterface()
	}

	// When bonding is enabled, skip per-interface config — IP goes on bond0.
	if o.cfg.BondInterfaces == "" {
		if err := writeNetworkForOS(rootDir, osFamily, iface, o.cfg.StaticIP, o.cfg.StaticGateway, o.cfg.DNSResolvers); err != nil {
			return err
		}
	}

	// Persist bond configuration if present.
	if o.cfg.BondInterfaces != "" {
		if err := persistBondConfig(rootDir, osFamily, o.cfg); err != nil {
			o.log.Warn("Failed to persist bond configuration", "error", err)
		}
	}

	// Persist VLAN configuration if present.
	if o.cfg.VLANs != "" {
		if err := persistVLANConfig(rootDir, osFamily, o.cfg); err != nil {
			o.log.Warn("Failed to persist VLAN configuration", "error", err)
		}
	}

	return nil
}

// writeNetworkForOS dispatches to the correct network config writer for the OS family.
func writeNetworkForOS(rootDir, osFamily, iface, staticIP, gateway, dnsResolvers string) error {
	if err := validateNetName(iface); err != nil {
		return fmt.Errorf("network interface: %w", err)
	}
	switch osFamily {
	case "ubuntu":
		return writeNetplan(rootDir, iface, staticIP, gateway, dnsResolvers)
	case "flatcar":
		return writeSystemdNetworkd(rootDir, iface, staticIP, gateway, dnsResolvers)
	case "rhel":
		return writeNetworkManager(rootDir, iface, staticIP, gateway, dnsResolvers)
	default:
		return writeNetplan(rootDir, iface, staticIP, gateway, dnsResolvers)
	}
}

// detectOSFamily reads /etc/os-release in the chroot to determine the OS.
func detectOSFamily(rootDir string) string {
	data, err := os.ReadFile(filepath.Join(rootDir, "etc", "os-release"))
	if err != nil {
		slog.Warn("Could not read os-release, defaulting to ubuntu", "error", err)
		return "ubuntu"
	}
	content := strings.ToLower(string(data))
	switch {
	case strings.Contains(content, "ubuntu"):
		return "ubuntu"
	case strings.Contains(content, "flatcar"):
		return "flatcar"
	case strings.Contains(content, "rhel"), strings.Contains(content, "centos"), strings.Contains(content, "rocky"):
		return "rhel"
	default:
		return "ubuntu"
	}
}

// writeNetplan generates a netplan YAML config for Ubuntu/Debian systems.
func writeNetplan(rootDir, iface, staticIP, gateway, dnsResolvers string) error {
	netplanDir := filepath.Join(rootDir, "etc", "netplan")
	if err := os.MkdirAll(netplanDir, 0o755); err != nil {
		return fmt.Errorf("create netplan directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("# Generated by BOOTy provisioner — do not edit\n")
	buf.WriteString("network:\n")
	buf.WriteString("  version: 2\n")
	buf.WriteString("  renderer: networkd\n")

	buf.WriteString("  ethernets:\n")
	fmt.Fprintf(&buf, "    %s:\n", iface)

	if staticIP == "" {
		buf.WriteString("      dhcp4: true\n")
	} else {
		writeNetplanStatic(&buf, staticIP, gateway, dnsResolvers)
	}

	path := filepath.Join(netplanDir, "01-booty-provisioned.yaml")
	if err := os.WriteFile(path, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("writing netplan config %s: %w", path, err)
	}
	return nil
}

// writeNetplanStatic writes static IP configuration into a netplan buffer.
func writeNetplanStatic(buf *strings.Builder, staticIP, gateway, dnsResolvers string) {
	fmt.Fprintf(buf, "      addresses: [%q]\n", staticIP)
	if gateway != "" {
		ip := parseGateway(gateway)
		if ip != nil {
			if ip.To4() != nil {
				fmt.Fprintf(buf, "      gateway4: %s\n", ip)
			} else {
				fmt.Fprintf(buf, "      gateway6: %s\n", ip)
			}
		}
	}
	if dnsResolvers != "" {
		buf.WriteString("      nameservers:\n")
		buf.WriteString("        addresses: [")
		first := true
		for _, dns := range strings.Split(dnsResolvers, ",") {
			dns = strings.TrimSpace(dns)
			if dns == "" {
				continue
			}
			if !first {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%q", dns)
			first = false
		}
		buf.WriteString("]\n")
	}
}

// writeSystemdNetworkd generates systemd-networkd .network files for Flatcar.
func writeSystemdNetworkd(rootDir, iface, staticIP, gateway, dnsResolvers string) error {
	networkDir := filepath.Join(rootDir, "etc", "systemd", "network")
	if err := os.MkdirAll(networkDir, 0o755); err != nil {
		return fmt.Errorf("create systemd network directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("# Generated by BOOTy provisioner\n")
	buf.WriteString("[Match]\n")
	fmt.Fprintf(&buf, "Name=%s\n\n", iface)
	buf.WriteString("[Network]\n")

	if staticIP == "" {
		buf.WriteString("DHCP=yes\n")
	} else {
		writeNetworkdStatic(&buf, staticIP, gateway, dnsResolvers)
	}

	path := filepath.Join(networkDir, "10-booty.network")
	if err := os.WriteFile(path, []byte(buf.String()), 0o644); err != nil {
		return fmt.Errorf("writing networkd config %s: %w", path, err)
	}
	return nil
}

// writeNetworkdStatic writes static IP configuration into a systemd-networkd buffer.
func writeNetworkdStatic(buf *strings.Builder, staticIP, gateway, dnsResolvers string) {
	fmt.Fprintf(buf, "Address=%s\n", staticIP)
	if gateway != "" {
		ip := parseGateway(gateway)
		if ip != nil {
			fmt.Fprintf(buf, "Gateway=%s\n", ip)
		}
	}
	if dnsResolvers != "" {
		for _, dns := range strings.Split(dnsResolvers, ",") {
			dns = strings.TrimSpace(dns)
			if dns != "" {
				fmt.Fprintf(buf, "DNS=%s\n", dns)
			}
		}
	}
}

// parseGateway extracts a net.IP from a gateway string, stripping any CIDR mask.
func parseGateway(gateway string) net.IP {
	// Strip CIDR mask if present (e.g. "10.0.1.1/24" -> "10.0.1.1").
	if idx := strings.IndexByte(gateway, '/'); idx >= 0 {
		gateway = gateway[:idx]
	}
	return net.ParseIP(gateway)
}

// detectPrimaryInterface returns the name of the first non-loopback interface.
func detectPrimaryInterface() string {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "eth0"
	}
	for _, iface := range ifaces {
		if iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		if iface.Flags&net.FlagUp != 0 {
			return iface.Name
		}
	}
	return "eth0"
}

// writeNetworkManager generates NetworkManager INI keyfile configs for RHEL.
func writeNetworkManager(rootDir, iface, staticIP, gateway, dnsResolvers string) error {
	nmDir := filepath.Join(rootDir, "etc", "NetworkManager", "system-connections")
	if err := os.MkdirAll(nmDir, 0o755); err != nil {
		return fmt.Errorf("create NetworkManager directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("[connection]\n")
	fmt.Fprintf(&buf, "id=booty-%s\n", iface)
	buf.WriteString("type=ethernet\n")
	buf.WriteString("autoconnect=true\n\n")
	buf.WriteString("[ethernet]\n\n")

	if staticIP == "" {
		buf.WriteString("[ipv4]\nmethod=auto\n")
	} else {
		buf.WriteString("[ipv4]\nmethod=manual\n")
		fmt.Fprintf(&buf, "addresses=%s\n", staticIP)
		writeNMGateway(&buf, gateway)
		if dnsResolvers != "" {
			dns := strings.ReplaceAll(dnsResolvers, ",", ";")
			fmt.Fprintf(&buf, "dns=%s;\n", dns)
		}
	}

	path := filepath.Join(nmDir, fmt.Sprintf("booty-%s.nmconnection", iface))
	if err := os.WriteFile(path, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("writing NetworkManager config %s: %w", path, err)
	}
	return nil
}

// writeNMGateway appends the gateway line to a NetworkManager config if valid.
func writeNMGateway(buf *strings.Builder, gateway string) {
	if gateway == "" {
		return
	}
	ip := parseGateway(gateway)
	if ip != nil {
		fmt.Fprintf(buf, "gateway=%s\n", ip)
	}
}

// persistBondConfig writes bond configuration into the target OS.
func persistBondConfig(rootDir, osFamily string, cfg *config.MachineConfig) error {
	var bondIfaces []string
	for _, iface := range strings.Split(cfg.BondInterfaces, ",") {
		iface = strings.TrimSpace(iface)
		if iface == "" {
			continue
		}
		bondIfaces = append(bondIfaces, iface)
	}
	if len(bondIfaces) < 2 {
		return nil
	}
	for _, iface := range bondIfaces {
		if err := validateNetName(iface); err != nil {
			return fmt.Errorf("bond interface: %w", err)
		}
	}
	bondMode := cfg.BondMode
	if bondMode == "" {
		bondMode = "802.3ad"
	}

	switch osFamily {
	case "ubuntu":
		return writeBondNetplan(rootDir, bondIfaces, bondMode, cfg)
	case "flatcar":
		return writeBondSystemd(rootDir, bondIfaces, bondMode, cfg)
	case "rhel":
		return writeBondNetworkManager(rootDir, bondIfaces, bondMode, cfg)
	default:
		return writeBondNetplan(rootDir, bondIfaces, bondMode, cfg)
	}
}

func writeBondNetplan(rootDir string, ifaces []string, mode string, cfg *config.MachineConfig) error {
	netplanDir := filepath.Join(rootDir, "etc", "netplan")
	if err := os.MkdirAll(netplanDir, 0o755); err != nil {
		return fmt.Errorf("create netplan directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("# BOOTy bond configuration\n")
	buf.WriteString("network:\n")
	buf.WriteString("  version: 2\n")
	buf.WriteString("  bonds:\n")
	buf.WriteString("    bond0:\n")
	buf.WriteString("      interfaces:\n")
	for _, iface := range ifaces {
		fmt.Fprintf(&buf, "        - %s\n", strings.TrimSpace(iface))
	}
	fmt.Fprintf(&buf, "      parameters:\n        mode: %s\n", mode)

	if cfg.StaticIP != "" {
		fmt.Fprintf(&buf, "      addresses: [%q]\n", cfg.StaticIP)
		if gw := parseGateway(cfg.StaticGateway); gw != nil {
			if gw.To4() != nil {
				fmt.Fprintf(&buf, "      gateway4: %s\n", gw)
			} else {
				fmt.Fprintf(&buf, "      gateway6: %s\n", gw)
			}
		}
		if cfg.DNSResolvers != "" {
			fmt.Fprintf(&buf, "      nameservers:\n        addresses: [%s]\n", cfg.DNSResolvers)
		}
	} else {
		buf.WriteString("      dhcp4: true\n")
	}

	path := filepath.Join(netplanDir, "02-booty-bond.yaml")
	if err := os.WriteFile(path, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("writing bond netplan: %w", err)
	}
	return nil
}

func writeBondSystemd(rootDir string, ifaces []string, mode string, cfg *config.MachineConfig) error {
	networkDir := filepath.Join(rootDir, "etc", "systemd", "network")
	if err := os.MkdirAll(networkDir, 0o755); err != nil {
		return fmt.Errorf("create systemd network directory: %w", err)
	}

	// Write .netdev for bond
	var netdev strings.Builder
	netdev.WriteString("[NetDev]\nName=bond0\nKind=bond\n\n")
	fmt.Fprintf(&netdev, "[Bond]\nMode=%s\n", mode)
	netdevPath := filepath.Join(networkDir, "10-bond0.netdev")
	if err := os.WriteFile(netdevPath, []byte(netdev.String()), 0o644); err != nil {
		return fmt.Errorf("writing bond netdev: %w", err)
	}

	// Write .network to attach slaves
	for i, iface := range ifaces {
		var slave strings.Builder
		slave.WriteString("[Match]\n")
		fmt.Fprintf(&slave, "Name=%s\n\n", strings.TrimSpace(iface))
		slave.WriteString("[Network]\nBond=bond0\n")
		slavePath := filepath.Join(networkDir, fmt.Sprintf("10-bond0-slave%d.network", i))
		if err := os.WriteFile(slavePath, []byte(slave.String()), 0o644); err != nil {
			return fmt.Errorf("writing bond slave config: %w", err)
		}
	}

	// Write .network for bond0 itself
	var bondNet strings.Builder
	bondNet.WriteString("[Match]\nName=bond0\n\n[Network]\n")
	if cfg.StaticIP != "" {
		fmt.Fprintf(&bondNet, "Address=%s\n", cfg.StaticIP)
		if gw := parseGateway(cfg.StaticGateway); gw != nil {
			fmt.Fprintf(&bondNet, "Gateway=%s\n", gw)
		}
		if cfg.DNSResolvers != "" {
			for _, dns := range strings.Split(cfg.DNSResolvers, ",") {
				fmt.Fprintf(&bondNet, "DNS=%s\n", strings.TrimSpace(dns))
			}
		}
	} else {
		bondNet.WriteString("DHCP=yes\n")
	}
	bondNetPath := filepath.Join(networkDir, "10-bond0.network")
	if err := os.WriteFile(bondNetPath, []byte(bondNet.String()), 0o644); err != nil {
		return fmt.Errorf("writing bond network: %w", err)
	}
	return nil
}

func writeBondNetworkManager(rootDir string, ifaces []string, mode string, cfg *config.MachineConfig) error {
	nmDir := filepath.Join(rootDir, "etc", "NetworkManager", "system-connections")
	if err := os.MkdirAll(nmDir, 0o755); err != nil {
		return fmt.Errorf("create NetworkManager directory: %w", err)
	}

	// Bond master
	var master strings.Builder
	master.WriteString("[connection]\nid=bond0\ntype=bond\nautoconnect=true\n\n")
	fmt.Fprintf(&master, "[bond]\nmode=%s\n\n", mode)
	if cfg.StaticIP != "" {
		fmt.Fprintf(&master, "[ipv4]\nmethod=manual\naddresses=%s\n", cfg.StaticIP)
	} else {
		master.WriteString("[ipv4]\nmethod=auto\n")
	}
	masterPath := filepath.Join(nmDir, "bond0.nmconnection")
	if err := os.WriteFile(masterPath, []byte(master.String()), 0o600); err != nil {
		return fmt.Errorf("writing bond master: %w", err)
	}

	// Bond slaves
	for i, iface := range ifaces {
		ifaceName := strings.TrimSpace(iface)
		var slave strings.Builder
		fmt.Fprintf(&slave, "[connection]\nid=bond0-slave%d\ntype=ethernet\nmaster=bond0\nslave-type=bond\n\n", i)
		fmt.Fprintf(&slave, "[ethernet]\n\n[match]\ninterface-name=%s\n", ifaceName)
		slavePath := filepath.Join(nmDir, fmt.Sprintf("bond0-slave%d.nmconnection", i))
		if err := os.WriteFile(slavePath, []byte(slave.String()), 0o600); err != nil {
			return fmt.Errorf("writing bond slave: %w", err)
		}
	}
	return nil
}

// persistVLANConfig writes VLAN configuration into the target OS.
// VLANs format: "200:eno1:10.200.0.42/24,300:eno2".
func persistVLANConfig(rootDir, osFamily string, cfg *config.MachineConfig) error {
	for _, vlanSpec := range strings.Split(cfg.VLANs, ",") {
		parts := strings.SplitN(strings.TrimSpace(vlanSpec), ":", 3)
		if len(parts) < 2 {
			continue
		}
		vlanID := parts[0]
		parentIface := parts[1]
		ip := ""
		if len(parts) == 3 {
			ip = parts[2]
		}

		if err := validateNetName(vlanID); err != nil {
			return fmt.Errorf("VLAN ID: %w", err)
		}
		if err := validateNetName(parentIface); err != nil {
			return fmt.Errorf("VLAN parent interface: %w", err)
		}

		switch osFamily {
		case "ubuntu":
			if err := writeVLANNetplan(rootDir, vlanID, parentIface, ip); err != nil {
				return err
			}
		case "flatcar":
			if err := writeVLANSystemd(rootDir, vlanID, parentIface, ip); err != nil {
				return err
			}
		default:
			if err := writeVLANNetplan(rootDir, vlanID, parentIface, ip); err != nil {
				return err
			}
		}
	}
	return nil
}

func writeVLANNetplan(rootDir, vlanID, parent, ip string) error {
	netplanDir := filepath.Join(rootDir, "etc", "netplan")
	if err := os.MkdirAll(netplanDir, 0o755); err != nil {
		return fmt.Errorf("create netplan directory: %w", err)
	}

	var buf strings.Builder
	buf.WriteString("# BOOTy VLAN configuration\nnetwork:\n  version: 2\n  vlans:\n")
	fmt.Fprintf(&buf, "    vlan%s:\n      id: %s\n      link: %s\n", vlanID, vlanID, parent)
	if ip != "" {
		fmt.Fprintf(&buf, "      addresses: [%q]\n", ip)
	} else {
		buf.WriteString("      dhcp4: true\n")
	}

	path := filepath.Join(netplanDir, fmt.Sprintf("03-booty-vlan%s.yaml", vlanID))
	if err := os.WriteFile(path, []byte(buf.String()), 0o600); err != nil {
		return fmt.Errorf("writing VLAN netplan: %w", err)
	}
	return nil
}

func writeVLANSystemd(rootDir, vlanID, parent, ip string) error {
	networkDir := filepath.Join(rootDir, "etc", "systemd", "network")
	if err := os.MkdirAll(networkDir, 0o755); err != nil {
		return fmt.Errorf("create systemd network directory: %w", err)
	}

	vlanName := fmt.Sprintf("vlan%s", vlanID)

	// .netdev
	var netdev strings.Builder
	fmt.Fprintf(&netdev, "[NetDev]\nName=%s\nKind=vlan\n\n[VLAN]\nId=%s\n", vlanName, vlanID)
	netdevPath := filepath.Join(networkDir, fmt.Sprintf("20-%s.netdev", vlanName))
	if err := os.WriteFile(netdevPath, []byte(netdev.String()), 0o644); err != nil {
		return fmt.Errorf("writing VLAN netdev: %w", err)
	}

	// .network for VLAN interface
	var network strings.Builder
	fmt.Fprintf(&network, "[Match]\nName=%s\n\n[Network]\n", vlanName)
	if ip != "" {
		fmt.Fprintf(&network, "Address=%s\n", ip)
	} else {
		network.WriteString("DHCP=yes\n")
	}
	networkPath := filepath.Join(networkDir, fmt.Sprintf("20-%s.network", vlanName))
	if err := os.WriteFile(networkPath, []byte(network.String()), 0o644); err != nil {
		return fmt.Errorf("writing VLAN network: %w", err)
	}

	// Add VLAN to parent interface. Use 05- prefix so this file takes
	// precedence over the base 10-booty.network for the same interface name.
	parentNetPath := filepath.Join(networkDir, fmt.Sprintf("05-%s-vlan.network", parent))
	var parentNet strings.Builder
	fmt.Fprintf(&parentNet, "[Match]\nName=%s\n\n[Network]\nVLAN=%s\n", parent, vlanName)
	if err := os.WriteFile(parentNetPath, []byte(parentNet.String()), 0o644); err != nil {
		return fmt.Errorf("writing parent VLAN network: %w", err)
	}
	return nil
}
