//go:build linux

package provision

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"

	"github.com/telekom/BOOTy/pkg/config"
)

const overlayRootLocalConfigPath = "etc/overlayroot.local.conf"

// ConfigureOverlayFS writes target-root overlayFS configuration for Ubuntu
// images. It deliberately does not remount BOOTy's running root filesystem.
func (c *Configurator) ConfigureOverlayFS(cfg *config.OverlayFSConfig, osFamily string) error {
	if cfg == nil || !cfg.Enabled {
		return nil
	}
	if !strings.EqualFold(strings.TrimSpace(osFamily), "ubuntu") {
		return fmt.Errorf("overlayFS configuration requires osFamily=ubuntu")
	}

	data, err := renderOverlayRootConfig(cfg)
	if err != nil {
		return err
	}
	path := filepath.Join(c.rootDir, overlayRootLocalConfigPath)
	if err := ensureWithinRoot(c.rootDir, path); err != nil {
		return fmt.Errorf("overlayroot config path: %w", err)
	}
	if err := ensureTargetParentWithinRoot(c.rootDir, filepath.Dir(path)); err != nil {
		return fmt.Errorf("overlayroot config directory: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("creating overlayroot config directory: %w", err)
	}
	if err := ensureTargetParentWithinRoot(c.rootDir, filepath.Dir(path)); err != nil {
		return fmt.Errorf("overlayroot config directory: %w", err)
	}
	if err := writeFileAtomic(path, []byte(data), 0o644); err != nil {
		return fmt.Errorf("writing overlayroot config: %w", err)
	}
	if err := c.prepareOverlayFSDirs(cfg); err != nil {
		return err
	}
	slog.Info("configured target overlayFS", "path", path, "mode", overlayMode(cfg.Mode))
	return nil
}

func (c *Configurator) prepareOverlayFSDirs(cfg *config.OverlayFSConfig) error {
	for _, dir := range []string{cfg.UpperDir, cfg.WorkDir} {
		target, err := overlayFSTargetDir(c.rootDir, dir)
		if err != nil {
			return err
		}
		if target == "" {
			continue
		}
		if err := ensureWithinRoot(c.rootDir, target); err != nil {
			return fmt.Errorf("overlayFS directory %s: %w", dir, err)
		}
		if err := ensureTargetParentWithinRoot(c.rootDir, target); err != nil {
			return fmt.Errorf("overlayFS directory %s: %w", dir, err)
		}
		if err := os.MkdirAll(target, 0o755); err != nil {
			return fmt.Errorf("creating overlayFS directory %s: %w", dir, err)
		}
		if err := ensureTargetParentWithinRoot(c.rootDir, target); err != nil {
			return fmt.Errorf("overlayFS directory %s: %w", dir, err)
		}
	}
	return nil
}

func renderOverlayRootConfig(cfg *config.OverlayFSConfig) (string, error) {
	spec, err := overlayRootSpec(cfg)
	if err != nil {
		return "", err
	}
	return "# Generated by BOOTy. Requires Ubuntu overlayroot in the target image initramfs.\n" +
		"# Kernel command line overlayroot=disabled overrides this file for rollback.\n" +
		"overlayroot_cfgdisk=\"disabled\"\n" +
		"overlayroot=" + strconv.Quote(spec) + "\n", nil
}

func overlayRootSpec(cfg *config.OverlayFSConfig) (string, error) {
	mode := overlayMode(cfg.Mode)
	if err := validateOverlayRootValue("overlayFS.device", cfg.Device); err != nil {
		return "", err
	}
	if err := validateOverlayRootValue("overlayFS.directory", cfg.Directory); err != nil {
		return "", err
	}
	if cfg.TimeoutSec < 0 {
		return "", fmt.Errorf("overlayFS timeoutSec must be non-negative")
	}
	common := overlayRootCommonOptions(cfg)
	switch mode {
	case config.OverlayFSModeTmpfs:
		if strings.TrimSpace(cfg.Device) != "" {
			return "", fmt.Errorf("overlayFS device is only valid for device mode")
		}
		if cfg.TimeoutSec != 0 {
			return "", fmt.Errorf("overlayFS timeoutSec is only valid for device mode")
		}
		return "tmpfs:" + strings.Join(common, ","), nil
	case config.OverlayFSModeDevice:
		device := strings.TrimSpace(cfg.Device)
		if device == "" {
			return "", fmt.Errorf("overlayFS device is required for device mode")
		}
		options := append([]string{"dev=" + device}, overlayRootDeviceOptions(cfg)...)
		options = append(options, common...)
		return "device:" + strings.Join(options, ","), nil
	default:
		return "", fmt.Errorf("unsupported overlayFS mode %q", cfg.Mode)
	}
}

func validateOverlayRootValue(name, value string) error {
	trimmed := strings.TrimSpace(value)
	if value != "" && trimmed == "" {
		return fmt.Errorf("%s must not be blank", name)
	}
	for _, r := range value {
		if unicode.IsControl(r) || unicode.IsSpace(r) || r == '"' || r == '\'' || r == ',' {
			return fmt.Errorf("%s contains unsafe character %q", name, r)
		}
	}
	if strings.Contains(trimmed, "..") {
		return fmt.Errorf("%s must not contain parent-directory segments", name)
	}
	return nil
}

func overlayFSTargetDir(root, dir string) (string, error) {
	trimmed := strings.TrimSpace(dir)
	if trimmed == "" {
		return "", nil
	}
	if !filepath.IsAbs(trimmed) {
		return "", fmt.Errorf("overlayFS directory %s must be absolute", dir)
	}
	if filepath.Clean(trimmed) == string(filepath.Separator) {
		return "", fmt.Errorf("overlayFS directory %s must not be root", dir)
	}
	if containsParentPathSegment(trimmed) {
		return "", fmt.Errorf("overlayFS directory %s must not contain parent-directory segments", dir)
	}
	return filepath.Join(root, strings.TrimPrefix(filepath.Clean(trimmed), string(filepath.Separator))), nil
}

func containsParentPathSegment(dir string) bool {
	for _, part := range strings.Split(dir, string(filepath.Separator)) {
		if part == ".." {
			return true
		}
	}
	return false
}

func overlayRootDeviceOptions(cfg *config.OverlayFSConfig) []string {
	if cfg.TimeoutSec <= 0 {
		return nil
	}
	return []string{fmt.Sprintf("timeout=%d", cfg.TimeoutSec)}
}

func overlayRootCommonOptions(cfg *config.OverlayFSConfig) []string {
	options := []string{
		boolOverlayRootOption("swap", cfg.Swap),
		boolOverlayRootOption("recurse", cfg.Recurse),
	}
	if cfg.Debug {
		options = append(options, "debug=1")
	}
	if dir := strings.TrimSpace(cfg.Directory); dir != "" {
		options = append(options, "dir="+dir)
	}
	return options
}

func boolOverlayRootOption(name string, value bool) string {
	if value {
		return name + "=1"
	}
	return name + "=0"
}

func overlayMode(mode string) string {
	normalized := strings.ToLower(strings.TrimSpace(mode))
	if normalized == "" {
		return config.OverlayFSModeTmpfs
	}
	return normalized
}
