package luks

import (
	"strings"
	"testing"
)

func TestGenerateCrypttab_Passphrase(t *testing.T) {
	targets := []Target{
		{Device: "/dev/sda3", MappedName: "root_crypt", MountPoint: "/"},
	}

	result := GenerateCrypttab(targets, UnlockPassphrase)

	if !strings.Contains(result, "root_crypt") {
		t.Error("missing mapped name")
	}
	if !strings.Contains(result, "/dev/sda3") {
		t.Error("missing device")
	}
	if !strings.Contains(result, "luks,discard") {
		t.Error("missing options")
	}
	if !strings.HasPrefix(result, "# Generated by BOOTy") {
		t.Error("missing header comment")
	}
}

func TestGenerateCrypttab_TPM2(t *testing.T) {
	targets := []Target{
		{Device: "/dev/sda3", MappedName: "root_crypt", MountPoint: "/"},
	}

	result := GenerateCrypttab(targets, UnlockTPM2)

	if !strings.Contains(result, "tpm2-device=auto") {
		t.Error("TPM2 method should have tpm2-device=auto option")
	}
}

func TestGenerateCrypttab_Clevis(t *testing.T) {
	targets := []Target{
		{Device: "/dev/nvme0n1p3", MappedName: "data_crypt", MountPoint: "/data"},
	}

	result := GenerateCrypttab(targets, UnlockClevis)

	if !strings.Contains(result, "_netdev") {
		t.Error("clevis method should have _netdev option")
	}
}

func TestGenerateCrypttab_KeyFile(t *testing.T) {
	targets := []Target{
		{Device: "/dev/sda3", MappedName: "root_crypt", MountPoint: "/"},
	}

	result := GenerateCrypttab(targets, UnlockKeyFile)

	if !strings.Contains(result, "keyfile-timeout=30s") {
		t.Error("keyfile method should have keyfile-timeout option")
	}
}

func TestGenerateCrypttab_MultipleTargets(t *testing.T) {
	targets := []Target{
		{Device: "/dev/sda3", MappedName: "root_crypt", MountPoint: "/"},
		{Device: "/dev/sda4", MappedName: "data_crypt", MountPoint: "/data"},
	}

	result := GenerateCrypttab(targets, UnlockPassphrase)

	if !strings.Contains(result, "root_crypt") {
		t.Error("missing first target")
	}
	if !strings.Contains(result, "data_crypt") {
		t.Error("missing second target")
	}
}

func TestGenerateCrypttab_DefaultMethod(t *testing.T) {
	targets := []Target{
		{Device: "/dev/sda3", MappedName: "root_crypt", MountPoint: "/"},
	}

	result := GenerateCrypttab(targets, UnlockMethod("unknown"))

	if !strings.Contains(result, "luks,discard") {
		t.Error("unknown method should default to luks,discard")
	}
}

func TestMappedPath(t *testing.T) {
	got := MappedPath("root_crypt")
	want := "/dev/mapper/root_crypt"
	if got != want {
		t.Errorf("MappedPath = %q, want %q", got, want)
	}
}

func TestConfig_Defaults(t *testing.T) {
	cfg := &Config{
		Enabled:      true,
		UnlockMethod: UnlockTPM2,
		Passphrase:   "test-pass",
	}

	if cfg.Cipher != "" {
		t.Error("cipher should default to empty (handled in Format)")
	}
	if cfg.KeySize != 0 {
		t.Error("keySize should default to 0 (handled in Format)")
	}
	if cfg.Hash != "" {
		t.Error("hash should default to empty (handled in Format)")
	}
}

func TestUnlockMethodConstants(t *testing.T) {
	tests := []struct {
		method   UnlockMethod
		expected string
	}{
		{UnlockPassphrase, "passphrase"},
		{UnlockTPM2, "tpm2"},
		{UnlockClevis, "clevis"},
		{UnlockKeyFile, "keyfile"},
	}

	for _, tc := range tests {
		if string(tc.method) != tc.expected {
			t.Errorf("UnlockMethod %q != %q", tc.method, tc.expected)
		}
	}
}
