package luks

import (
	"fmt"
	"strings"
)

// DefaultKeyFilePath is the standard path for LUKS key files in initramfs.
const DefaultKeyFilePath = "/etc/luks/keyfile"

// GenerateCrypttab creates /etc/crypttab content for the provisioned OS.
func GenerateCrypttab(targets []Target, method UnlockMethod) string {
	lines := make([]string, 0, 1+len(targets))
	lines = append(lines, "# Generated by BOOTy provisioner")

	for _, t := range targets {
		if strings.TrimSpace(t.MappedName) == "" || strings.TrimSpace(t.Device) == "" {
			continue
		}
		var options string
		switch method {
		case UnlockPassphrase:
			options = "luks,discard"
		case UnlockTPM2:
			options = "luks,discard,tpm2-device=auto"
		case UnlockClevis:
			options = "luks,discard,_netdev"
		case UnlockKeyFile:
			options = "luks,discard,keyfile-timeout=30s"
		default:
			options = "luks,discard"
		}
		keyField := "none"
		if method == UnlockKeyFile {
			keyField = DefaultKeyFilePath
		}
		lines = append(lines, fmt.Sprintf("%s %s %s %s",
			t.MappedName, t.Device, keyField, options))
	}
	return strings.Join(lines, "\n") + "\n"
}
